"""agregar_cuescore

Revision ID: fc6e5e8f9763
Revises: 
Create Date: 2026-07-18 11:48:23.891522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6e5e8f9763'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_circuito')
    with op.batch_alter_table('circuito', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    with op.batch_alter_table('documento_circuito', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('temporada',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'temporada', ['temporada_id'], ['id'])

    with op.batch_alter_table('temporada', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuescore_player_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cuescore_player_id_verified_at', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cuescore_player_id_verified_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('cuescore_player_id_verified_by')
        batch_op.drop_column('cuescore_player_id_verified_at')
        batch_op.drop_column('cuescore_player_id')

    with op.batch_alter_table('temporada', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('documento_circuito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('temporada',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('circuito', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('_alembic_tmp_circuito',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), nullable=False),
    sa.Column('calendario_pdf', sa.VARCHAR(length=200), nullable=True),
    sa.Column('normativa_pdf', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
